name: CI
on:
    workflow_dispatch:
        inputs:
            ambiente:
                type: choice
                description: 'Ambiente de deploy'
                options:
                    - dev
                    - staging
                    - prod
                default: dev
            provider:
                type: choice
                description: 'Cloud provider para deploy'
                options:
                    - google
                    - aws
                default: google 
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4.1.5

            - name: Login to Docker Hub
              run: echo "Aqui estamos simulando o login no Docker Hub"

            - name: Build Docker image
              run: echo "Aqui estamos simulando o build da imagem"
    deploy:
        needs: build
        uses: vinicius3516/devops-tools/.github/workflows/cd.yml@main
        with:
            manifest: ./k8s/deployment.yaml
            provider: ${{ github.event.inputs.provider }}
            ambiente: ${{ github.event.inputs.ambiente }}